### PR TITLE
chore: init repo

### PR DESCRIPTION
**Pull request by affanshahid**
This PR adds artifacts generated by tree-sitter for the Exograph grammar.

### CODE REVIEW

**Comment by ramnivas** [comment]
Thanks for this PR. 

I have a couple of questions (context: I know nothing about the Zed extension system; I have been curious about the Zed editor, but never had time to try it out).

Are all these files necessary? I don't see any many files in, for example, https://github.com/victorhqc/tree-sitter-prisma or https://github.com/11bit/tree-sitter-graphql. Specifically, I don't see Swift or Python files. So wanted to check.

**Comment by affanshahid** [comment]
These are all auto-generated by `tree-sitter generate`. It auto generates bindings to the grammar for use in multiple languages, we don't really need them all, just the node and rust ones I suppose. I think tree-sitter added more bindings recently, which is why you'll see them for newer grammars and not older ones. For example:

https://github.com/camdencheek/tree-sitter-dockerfile/tree/main/bindings
https://github.com/tree-sitter/tree-sitter-java/tree/master/bindings
https://github.com/tree-sitter/tree-sitter-typescript/tree/master/bindings

(Last two are official repos by the tree-sitter team)

**Comment by affanshahid** [comment]
Just to add context, the tree-sitter artifacts are not really part of the Zed extension system. Zed extensions just depend on a valid tree-sitter grammar for syntax highlighting. So tree-sitter just provides the AST and the Zed extension simply piggy-backs on it to add syntax highlighting.

**Comment by ramnivas** [comment]
Merged and renamed the repo to tree-sitter-exograph as that seems to the convention (earlier, I thought the `exograph` org name will suffice as the namespace).

**Pull request merged**
